import type { ImageSourcePropType } from "react-native";

export const card_suits = ["hearts", "diamonds", "clubs", "spades"] as const;
export const card_values = [2, 3, 4, 5, 6, 7, 8, 9, 10, "J", "Q", "K", "A"] as const;

export type Suit = (typeof card_suits)[number];
export type Rank = (typeof card_values)[number];

export type TCard = {
  id: string;
  suit: Suit;
  rank: Rank;
  chips: number;
  image: ImageSourcePropType;
};

export const all_cards = [
  {
    chips: 2,
    id: "2H",
    image: require("@/assets/decks/abandoned_deck.png"),
    rank: 2,
    suit: "hearts",
  },
  {
    chips: 3,
    id: "3H",
    image: require("@/assets/decks/abandoned_deck.png"),
    rank: 3,
    suit: "hearts",
  },
  {
    chips: 4,
    id: "4H",
    image: require("@/assets/decks/abandoned_deck.png"),
    rank: 4,
    suit: "hearts",
  },
  {
    chips: 5,
    id: "5H",
    image: require("@/assets/decks/abandoned_deck.png"),
    rank: 5,
    suit: "hearts",
  },
  {
    chips: 6,
    id: "6H",
    image: require("@/assets/decks/abandoned_deck.png"),
    rank: 6,
    suit: "hearts",
  },
  {
    chips: 7,
    id: "7H",
    image: require("@/assets/decks/abandoned_deck.png"),
    rank: 7,
    suit: "hearts",
  },
  {
    chips: 8,
    id: "8H",
    image: require("@/assets/decks/abandoned_deck.png"),
    rank: 8,
    suit: "hearts",
  },
  {
    chips: 9,
    id: "9H",
    image: require("@/assets/decks/abandoned_deck.png"),
    rank: 9,
    suit: "hearts",
  },
  {
    chips: 10,
    id: "10H",
    image: require("@/assets/decks/abandoned_deck.png"),
    rank: 10,
    suit: "hearts",
  },
  {
    chips: 10,
    id: "JH",
    image: require("@/assets/decks/abandoned_deck.png"),
    rank: "J",
    suit: "hearts",
  },
  {
    chips: 10,
    id: "QH",
    image: require("@/assets/decks/abandoned_deck.png"),
    rank: "Q",
    suit: "hearts",
  },
  {
    chips: 10,
    id: "KH",
    image: require("@/assets/decks/abandoned_deck.png"),
    rank: "K",
    suit: "hearts",
  },
  {
    chips: 11,
    id: "AH",
    image: require("@/assets/decks/abandoned_deck.png"),
    rank: "A",
    suit: "hearts",
  },
  {
    chips: 2,
    id: "2D",
    image: require("@/assets/decks/abandoned_deck.png"),
    rank: 2,
    suit: "diamonds",
  },
  {
    chips: 3,
    id: "3D",
    image: require("@/assets/decks/abandoned_deck.png"),
    rank: 3,
    suit: "diamonds",
  },
  {
    chips: 4,
    id: "4D",
    image: require("@/assets/decks/abandoned_deck.png"),
    rank: 4,
    suit: "diamonds",
  },
  {
    chips: 5,
    id: "5D",
    image: require("@/assets/decks/abandoned_deck.png"),
    rank: 5,
    suit: "diamonds",
  },
  {
    chips: 6,
    id: "6D",
    image: require("@/assets/decks/abandoned_deck.png"),
    rank: 6,
    suit: "diamonds",
  },
  {
    chips: 7,
    id: "7D",
    image: require("@/assets/decks/abandoned_deck.png"),
    rank: 7,
    suit: "diamonds",
  },
  {
    chips: 8,
    id: "8D",
    image: require("@/assets/decks/abandoned_deck.png"),
    rank: 8,
    suit: "diamonds",
  },
  {
    chips: 9,
    id: "9D",
    image: require("@/assets/decks/abandoned_deck.png"),
    rank: 9,
    suit: "diamonds",
  },
  {
    chips: 10,
    id: "10D",
    image: require("@/assets/decks/abandoned_deck.png"),
    rank: 10,
    suit: "diamonds",
  },
  {
    chips: 10,
    id: "JD",
    image: require("@/assets/decks/abandoned_deck.png"),
    rank: "J",
    suit: "diamonds",
  },
  {
    chips: 10,
    id: "QD",
    image: require("@/assets/decks/abandoned_deck.png"),
    rank: "Q",
    suit: "diamonds",
  },
  {
    chips: 10,
    id: "KD",
    image: require("@/assets/decks/abandoned_deck.png"),
    rank: "K",
    suit: "diamonds",
  },
  {
    chips: 11,
    id: "AD",
    image: require("@/assets/decks/abandoned_deck.png"),
    rank: "A",
    suit: "diamonds",
  },
  {
    chips: 2,
    id: "2C",
    image: require("@/assets/decks/abandoned_deck.png"),
    rank: 2,
    suit: "clubs",
  },
  {
    chips: 3,
    id: "3C",
    image: require("@/assets/decks/abandoned_deck.png"),
    rank: 3,
    suit: "clubs",
  },
  {
    chips: 4,
    id: "4C",
    image: require("@/assets/decks/abandoned_deck.png"),
    rank: 4,
    suit: "clubs",
  },
  {
    chips: 5,
    id: "5C",
    image: require("@/assets/decks/abandoned_deck.png"),
    rank: 5,
    suit: "clubs",
  },
  {
    chips: 6,
    id: "6C",
    image: require("@/assets/decks/abandoned_deck.png"),
    rank: 6,
    suit: "clubs",
  },
  {
    chips: 7,
    id: "7C",
    image: require("@/assets/decks/abandoned_deck.png"),
    rank: 7,
    suit: "clubs",
  },
  {
    chips: 8,
    id: "8C",
    image: require("@/assets/decks/abandoned_deck.png"),
    rank: 8,
    suit: "clubs",
  },
  {
    chips: 9,
    id: "9C",
    image: require("@/assets/decks/abandoned_deck.png"),
    rank: 9,
    suit: "clubs",
  },
  {
    chips: 10,
    id: "10C",
    image: require("@/assets/decks/abandoned_deck.png"),
    rank: 10,
    suit: "clubs",
  },
  {
    chips: 10,
    id: "JC",
    image: require("@/assets/decks/abandoned_deck.png"),
    rank: "J",
    suit: "clubs",
  },
  {
    chips: 10,
    id: "QC",
    image: require("@/assets/decks/abandoned_deck.png"),
    rank: "Q",
    suit: "clubs",
  },
  {
    chips: 10,
    id: "KC",
    image: require("@/assets/decks/abandoned_deck.png"),
    rank: "K",
    suit: "clubs",
  },
  {
    chips: 11,
    id: "AC",
    image: require("@/assets/decks/abandoned_deck.png"),
    rank: "A",
    suit: "clubs",
  },
  {
    chips: 2,
    id: "2S",
    image: require("@/assets/decks/abandoned_deck.png"),
    rank: 2,
    suit: "spades",
  },
  {
    chips: 3,
    id: "3S",
    image: require("@/assets/decks/abandoned_deck.png"),
    rank: 3,
    suit: "spades",
  },
  {
    chips: 4,
    id: "4S",
    image: require("@/assets/decks/abandoned_deck.png"),
    rank: 4,
    suit: "spades",
  },
  {
    chips: 5,
    id: "5S",
    image: require("@/assets/decks/abandoned_deck.png"),
    rank: 5,
    suit: "spades",
  },
  {
    chips: 6,
    id: "6S",
    image: require("@/assets/decks/abandoned_deck.png"),
    rank: 6,
    suit: "spades",
  },
  {
    chips: 7,
    id: "7S",
    image: require("@/assets/decks/abandoned_deck.png"),
    rank: 7,
    suit: "spades",
  },
  {
    chips: 8,
    id: "8S",
    image: require("@/assets/decks/abandoned_deck.png"),
    rank: 8,
    suit: "spades",
  },
  {
    chips: 9,
    id: "9S",
    image: require("@/assets/decks/abandoned_deck.png"),
    rank: 9,
    suit: "spades",
  },
  {
    chips: 10,
    id: "10S",
    image: require("@/assets/decks/abandoned_deck.png"),
    rank: 10,
    suit: "spades",
  },
  {
    chips: 10,
    id: "JS",
    image: require("@/assets/decks/abandoned_deck.png"),
    rank: "J",
    suit: "spades",
  },
  {
    chips: 10,
    id: "QS",
    image: require("@/assets/decks/abandoned_deck.png"),
    rank: "Q",
    suit: "spades",
  },
  {
    chips: 10,
    id: "KS",
    image: require("@/assets/decks/abandoned_deck.png"),
    rank: "K",
    suit: "spades",
  },
  {
    chips: 11,
    id: "AS",
    image: require("@/assets/cards/ace_of_spades.png"),
    rank: "A",
    suit: "spades",
  },
] satisfies TCard[];
